 development:
   adapter: mysql2
   encoding: utf8
   database: twitterDB
   username: root
   password: 
   host: 127.0.0.1
   port: 3306

 test:
   adapter: mysql2
   encoding: utf8
   database: twitterDB_test
   username: root
   password:
   host: 127.0.0.1
   port: 3306